### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by OpenSource03** [gamemann/XDP-Firewall#10]
Hello!

After rebooting a dedicated server, I'm getting `Error setting rlimit.`. Do you have any solutions?

Regards

**Comment by OpenSource03** [comment]
Actually, the issue above is that I tried to run it from non-root user, lol.

As I tried again, on a fresh installed OVH Ryzen 7 with 5.4.0-90-generic I experienced the following issue:

```
root@ns3169717:/home/ubuntu# xdpfw
Loaded XDP program in DRV/native mode.
Segmentation fault (core dumped)
```

Can we find the issue somehow?

**Comment by gamemann** [comment]
Hey @OpenSource03,

Are you able to run `gdb` to see if you can retrieve a backtrace (you can install it on Debian/Ubuntu via `apt install gdb` usually)?

You should be able to run:

```
gdb xdpfw
```

Afterwards, you'll be in the GDB interactive terminal. From there, you should be able execute `run` to execute the program. Once/if the program seg faults, you should be able to see the address it's seg faulting on along with some data. If you can, run `bt` to retrieve the backtrace and paste the results here if you can.

Can you also provide the outputs from `/etc/xdpfw/xdpfw.conf`?

Thank you!

**Comment by OpenSource03** [comment]
Hello! Sorry for the delay.

```
Starting program: /usr/bin/xdpfw 
Loaded XDP program in DRV/native mode.

Program received signal SIGSEGV, Segmentation fault.
0x000000000041f93f in main ()
```

```
interface = "enp1s0f0";
updatetime = 15;

filters = (
    {
        enabled = true,
        action = 1
    }
);
```

**Comment by OpenSource03** [comment]
Could be due to OVH's very weird network setup?
Here's my `/etc/netplan/50-cloud-init.yaml`

```
network:
    version: 2
    ethernets:
        enp1s0f0:
            accept-ra: false
            addresses:
            - 2001:41da:800:142e::/56
            dhcp4: true
            gateway6: 2001:41da:800:14ff:ff:ff:ff:ff
            match:
                macaddress: l0:50:99:dt:ae:c3
            nameservers:
                addresses:
                - 2001:41d0:3:163::1
            routes:
            { . . . unimportant }
            set-name: enp1s0f0
```

^^ Some of the addresses above are faked for security reasons.

Could that be due to dhcp4 that it's using to retrieve the ipv4 address or something...?
